#!/bin/bash

set -e

eval `ssh-agent -s`
ssh-add id_rsa

git clone git@github.com:tales-of-trinity/website.git _site
cd _site
git checkout gh-pages
cd ..
jekyll build
cd _site
git diff --exit-code
if [ $? -eq 0 ]; then
    echo "No changes to the output on this push; exiting."
    exit 0
fi

git config user.name "Travis CI"
git config user.email "tales.of.trinity.lps@gmail.com"
git add .
git commit -m "Travis deployment to github pages"

git push origin gh-pages